---
sudo: required
language: python

services:
  - docker

install:
  - pip install ome-ansible-molecule

script:
  - cd $PLAYBOOKDIR && molecule test -s $SCENARIO

env:
  - PLAYBOOKDIR=ansible-example-omero-onenode SCENARIO=default
  - PLAYBOOKDIR=ansible-example-omero-public-user SCENARIO=default
  - PLAYBOOKDIR=ansible-example-omero-three-nodes SCENARIO=default
  - PLAYBOOKDIR=ansible-example-omero-addons SCENARIO=centos7
  - PLAYBOOKDIR=ansible-example-omero-addons SCENARIO=ubuntu1804

# Docker-only
# - PLAYBOOKDIR=docker-example-omero-websockets
